#dubbo配置
spring:
  #datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.1.249:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
#    username: root
#    password: root

    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.249:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
      username: root
      password: root

# 最大连接数
      maxActive: 30
      #最小连接数
      minIdle: 5
      #最大等待时间
      maxWait: 10000

      #解决mysql8小时得问题
      validationQuery: SELECT 'x'
      #空闲链接检查时间间隔
      timeBetweenEvictionRunsMillis: 60000
      #空闲连接最小空闲时间
      minEvictableIdleTimeMilli: 300000

server:
  port: 8090
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml

